name: cli_info
sdkPath: .dvm/dart_sdk

packages:
  - packages/*
  - packages/cli_info_builder/example

command:
  bootstrap:
    environment:
      sdk: ^3.3.0
    dependencies:
      build: ^2.4.1
      build_config: ^1.1.1
      yaml: ^3.1.2
    dev_dependencies:
      build_test: ^2.2.2
      lints: ^3.0.0
      test: ^1.25.2
      build_runner: ^2.4.8

scripts:
  regenerate_code:
    run: dart run build_runner build -d
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner
  test:
    exec: dart test
    packageFilters:
      dependsOn: test

ide:
  intellij:
    enabled: false
