name: cli_info
sdkPath: .dvm/dart_sdk

packages:
  - packages/*

command:
  bootstrap:
    environment:
      sdk: ^3.3.0
    dev_dependencies:
      lints: ^3.0.0
      test: ^1.25.2

ide:
  intellij:
    enabled: false
