name: cli_info_builder
description: A package that provides a builder to generate a class to pack information about a Dart CLI application.
version: 1.0.1
repository: https://github.com/blendfactory/cli-info

environment:
  sdk: ^3.3.0

dependencies:
  dart_style: ^2.3.6
  build: ^2.4.1
  build_config: ^1.1.1
  yaml: ^3.1.2

dev_dependencies:
  build_test: ^2.2.2
  lints: ^3.0.0
  test: ^1.25.2
