name: cli_info_builder
description: A package that provides a builder to generate a class to pack information about a Dart CLI application.
version: 1.0.0
repository: https://github.com/blendfactory/cli-info

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
