name: cli_info_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/blendfactory/cli-info

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
