name: example
description: An example CLI application using cli_info_builder.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  cli_info:
    path: ../../cli_info

dev_dependencies:
  cli_info_builder:
    path: ..
  build_runner: ^2.4.8
