name: Publish to pub.dev

on:
  push:
    tags:
      - "cli_info-[0-9]+.[0-9]+.[0-9]+*"
      - "cli_info_builder-[0-9]+.[0-9]+.[0-9]+*"

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Publish packages with dry run
        run: melos publish --dry-run -y

      - name: Publish packages without dry run
        run: melos publish --no-dry-run -y
